archive/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<seriesName>.+)/$', views.series, name='series'),
]
    

spepArchiveDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('archive.urls', namespace='archive')),
]

archive/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
  name = models.CharField(max_length=128, unique=True)
  description = models.CharField(max_length=128)

  def __str__(self):
    return self.name
  
  class Meta:
    ordering = ["name"]

class Series(models.Model):
  name = models.CharField(max_length=128, unique=True)
  short_description = models.CharField(max_length=128, blank=True)
  long_description = models.TextField(blank=True)

  def __str__(self):
    return self.name

  class Meta:
    ordering = ["name"]

class Pastor(models.Model):
  name = models.CharField(max_length=128, unique=True)
  bio = models.TextField(blank=True)
  picture = models.URLField(blank=True)

  def __str__(self):
    return self.name

  class Meta:
    ordering = ["name"]

class Sermon(models.Model):
  sermon_title = models.CharField(max_length=128)
  pastor = models.ForeignKey(Pastor, null=True)
  verse = models.CharField(max_length=128)
  type = models.ForeignKey(Type)
  series = models.ForeignKey(Series, null=True)
  pub_date = models.DateField('Date Preached', blank=True)
  main_thought = models.CharField(max_length=512, blank=True)
  challenge = models.CharField(max_length=512, blank=True)
  url = models.CharField(max_length=1024)
  thumbnail = models.URLField(blank=True)
  video = models.URLField(blank=True)
  sequence_num = models.IntegerField(blank=True, null=True)

  def __str__(self):
    return self.sermon_title

  class Meta:
    ordering = ["-pub_date", "sequence_num"]

class Featured(models.Model):
  featured = models.OneToOneField(Sermon)

  def __str__(self):
    return self.featured.sermon_title

archive/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render

from .models import Featured, Series

def index(request):
    featured = Featured.objects.order_by('featured__pub_date')
    all_series = Series.objects.order_by('name')
    context = { 'featured': featured, 'all_series': all_series }
    return render(request, 'archive/index.html', context)

def series(request, seriesName):
    series = Series.objects.get(name=seriesName)
    sermons = series.sermon_set.order_by('pub_date', 'sequence_num')
    context = { 'sermons': sermons, 'series': series}
    return render(request, 'archive/series.html', context)

archive/templates/archive/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- saved from url=(0030)https://archive.spepmedia.com/ -->
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">



<!-- array(1) {
  [0]=>
  string(0) ""
}
1 - --><title> Sermon Archive</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script type="text/javascript" src="/lib/jquery/dist/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script type="text/javascript" src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://archive.spepmedia.com/style.css">
</head>
<body>
<div class="content-fluid">
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>SPEP Sermon Archive</h1>
  </div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<h4>
<a href="#">Home</a></h4>
</div>

</div>

<!--
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="well well-sm">
  {{text}}
</div>
</div>
</div>
-->
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <h3>Featured</h3>
  {% for feature in featured %}
   <div class="cover">
      <a href="{{ feature.featured.url }}">
      <img src="{{ feature.featured.thumbnail }}" width="100%" height="100%">
      <span class="info title">
        {{ feature.featured.sermon_title }}
      </span>
      <span class="info pastor">
        {{ feature.featured.pastor.name }}
      </span>
    </a>
  </div>
  {% endfor %}
  </div>
</div>


<div class="row">

<div class="col-md-8 col-md-offset-2">

<table class="table table-striped">
<thead>
<tr><th class="col-md-1"></th><th class="col-md-5">Series Name</th><th class="col-md-6">Description</th></tr>
</thead><tbody>
  {% for series in all_series %}
    <tr>
      <td><span class="glyphicon glyphicon-folder-close"></span></td>
      <td><a href="{%url 'archive:series' series.name %}">{{ series.name }}</td>
      <td>{{ series.short_description }}</td>
    </tr>
  {% endfor %}
</tbody></table>
</div>

</div>
</div>
<div class="footer">
  <div class="container">
    <p class="text-muted"><a href="http://spepchurch.org/">Severna Park EP Church (PCA)</a> :: Hosted on <a href="https://www.digitalocean.com/?refcode=c0167ae9a50a">DigitalOcean</a> :: <a href="http://validator.w3.org/check?uri=archive.spepmedia.com">Valid XHTML</a></p>
  </div>
</div>



<!--Debug info goes here


/debug-->
</body></html>

archive/templates/archive/series.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- saved from url=(0030)https://archive.spepmedia.com/ -->
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">



<!-- array(1) {
  [0]=>
  string(0) ""
}
1 - --><title>{{series.name}} - SPEP Sermon Archive</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script type="text/javascript" src="/lib/jquery/dist/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script type="text/javascript" src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://archive.spepmedia.com/style.css">
</head>
<body>
<div class="content-fluid">
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>SPEP Sermon Archive - {{series.name}}</h1>
  </div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<h4>
<a href="{% url 'archive:index' %}">Home</a> &gt;&gt; <a href="#">{{series.name}}</a></h4>
</div>

</div>

<!--
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="well well-sm">
  {{text}}
</div>
</div>
</div>
-->
<div class="row">

<div class="col-md-8 col-md-offset-2">

<table class="table table-striped">
<thead>
<tr><th class="col-md-3">Sermon Title</th><th class="col-md-3">Pastor</th><th class="col-md-3">Date Preached</th><th class="col-md-3">Verse</th></tr>
</thead><tbody>
  {% for sermon in sermons %}
    <tr>
      <td><a href="https://d2qmhswfbgwddq.cloudfront.net/{{sermon.url}}">{{ sermon.sermon_title }}</td>
      <td>{{ sermon.pastor.name }}</td>
      <td>{{ sermon.pub_date }}</td>
      <td>{{ sermon.verse}}</td>
    </tr>
  {% endfor %}
</tbody></table>
</div>

</div>
</div>
<div class="footer">
  <div class="container">
    <p class="text-muted"><a href="http://spepchurch.org/">Severna Park EP Church (PCA)</a>
      :: Hosted on <a href="https://www.digitalocean.com/?refcode=c0167ae9a50a">DigitalOcean</a>
      :: <a href="http://validator.w3.org/check?uri=archive.spepmedia.com">Valid XHTML</a></p>
  </div>
</div>



<!--Debug info goes here


/debug-->
</body></html>